version: '3'
services:
    mariadb:
        image: mariadb
        volumes:
            - 'dbdata:/var/lib/mysql'
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=findecs
            - MYSQL_USER=findecs
            - MYSQL_PASSWORD=S2GmVF8UH9wjFwaA
            - MYSQL_RANDOM_ROOT_PASSWORD=true
        restart: always
volumes:
    dbdata:
